//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team10Bsports
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int TransactionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CourtID { get; set; }
        public Nullable<System.DateTime> DateBook { get; set; }
        public Nullable<int> SlotID { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual CourtTable CourtTable { get; set; }
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual SlotTable SlotTable { get; set; }
    }
}
